// File to store all static strings

// Action Constants

const LOAD_MOVIES_LIST = 'GET_MOVIES_LIST';
const LOAD_MOVIES_PAGINATION = 'LOAD_MOVIES_PAGINATION';
const LOAD_MOVIE = 'LOAD_MOVIE';

// Mutation Constants

const SET_MOVIES_LIST = 'SET_MOVIES_LIST';
const SET_MOVIES_PAGINATION = 'SET_MOVIES_PAGINATION';
const SET_LOADER_STATUS = 'SET_LOADER_STATUS';
const SET_IS_ERROR = 'SET_IS_ERROR';
const SET_MOVIE = 'SET_MOVIE';

export default {
	ACTIONS: {
		LOAD_MOVIES_LIST,
		LOAD_MOVIES_PAGINATION,
    LOAD_MOVIE
	},
	MUTATIONS: {
		SET_MOVIES_LIST,
		SET_MOVIES_PAGINATION,
		SET_LOADER_STATUS,
		SET_IS_ERROR,
    SET_MOVIE
	}
};
